# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 21:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 18, 21, 46, 38, 971008, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
